dist: trusty
sudo: false
language: cpp
node_js: node
compiler: gcc
env:
  global:
    - ACE_ROOT=$TRAVIS_BUILD_DIR/ACE_TAO/ACE
    - TAO_ROOT=$TRAVIS_BUILD_DIR/ACE_TAO/TAO
    - DDS_ROOT=$TRAVIS_BUILD_DIR/OpenDDS
    - MPC_ROOT=$TRAVIS_BUILD_DIR/MPC
    - LD_LIBRARY_PATH=$ACE_ROOT/lib:$DDS_ROOT/lib:$LD_LIBRARY_PATH
    - NODE_VERSION="8"
matrix:
  include:
    - {os: osx, osx_image: xcode9.1, compiler: clang, env: 'COMPILER=clang++ NO_INLINE=1 OPENDDS_BRANCH=master'}
    - {os: osx, osx_image: xcode9.1, compiler: clang, env: 'COMPILER=clang++ NO_INLINE=1 OPENDDS_BRANCH=latest-release'}
    - {os: linux, env: OPENDDS_BRANCH=master}
    - {os: linux, env: OPENDDS_BRANCH=latest-release}
before_install:
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - git clone --depth 1 git://github.com/DOCGroup/MPC.git
  - git clone --depth 1 -b Latest_Micro git://github.com/DOCGroup/ACE_TAO.git
  - git clone --depth 1 -b $OPENDDS_BRANCH git://github.com/objectcomputing/OpenDDS.git
branches:
  only: master
before_script:
  - export
  - cd OpenDDS
  - ./configure --no-tests --macros=c++11=1
  - cd ..
  - npm install -g node-gyp
script:
  - make -C OpenDDS -sj6 DCPSInfoRepo_Main
  - npm install
  - export V8_ROOT=~/.node-gyp/$(node-gyp list)
  - export NAN_ROOT=$TRAVIS_BUILD_DIR/node_modules/nan
  - $ACE_ROOT/bin/mwc.pl -type gnuace -exclude ACE_TAO,OpenDDS
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$TRAVIS_BUILD_DIR/tools/v8stubs
  - make
  - cd test; ./run_test.pl
