---
name: "node-opendds CI"
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  schedule:
    - cron: '10 0 * * 0'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        node_version:
          - 12
          - 14
          - 16
        opendds_branch:
          - master
          - latest-release
        m:
          - {os: ubuntu-latest, dds_security: 1}
          - {os: ubuntu-latest, dds_security: 0}
          - {os: macos-latest, dds_security: 1}
          - {os: macos-latest, dds_security: 0}

    runs-on: ${{ matrix.m.os }}
    steps:
      - uses: actions/checkout@v2
      - name: 'Set environment variables'
        run: |-
          echo "ACE_ROOT=$GITHUB_WORKSPACE/ACE_TAO/ACE" >> $GITHUB_ENV
          echo "TAO_ROOT=$GITHUB_WORKSPACE/ACE_TAO/TAO" >> $GITHUB_ENV
          echo "DDS_ROOT=$GITHUB_WORKSPACE/OpenDDS" >> $GITHUB_ENV
          echo "MPC_ROOT=$GITHUB_WORKSPACE/MPC" >> $GITHUB_ENV
          echo "NVM_DIR=$GITHUB_WORKSPACE/nvm" >> $GITHUB_ENV
          echo "NAN_ROOT=$GITHUB_WORKSPACE/node_modules/nan" >> $GITHUB_ENV
          echo "npm_config_devdir=$GITHUB_WORKSPACE/opendds-node-gyp-devdir" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=$GITHUB_WORKSPACE/ACE_TAO/ACE/lib:$GITHUB_WORKSPACE/OpenDDS/lib:$GITHUB_WORKSPACE/tools/v8stubs:$LD_LIBRARY_PATH" >> $GITHUB_ENV
      - name: 'Checkout MPC'
        uses: actions/checkout@v2
        with:
          repository: DOCGroup/MPC
          path: MPC
          fetch-depth: 1
      - name: 'Checkout ACE_TAO'
        uses: actions/checkout@v2
        with:
          repository: DOCGroup/ACE_TAO
          ref: Latest_Micro
          path: ACE_TAO
          fetch-depth: 1
      - name: 'Checkout OpenDDS'
        uses: actions/checkout@v2
        with:
          repository: objectcomputing/OpenDDS
          ref: ${{ matrix.opendds_branch }}
          path: OpenDDS
          fetch-depth: 1
      - name: 'Install ssl and xerces (ubuntu)'
        run: |-
          sudo apt-get update
          sudo apt-get -y install libssl-dev libxerces-c-dev
        if: ${{ matrix.m.dds_security == 1 && matrix.m.os == 'ubuntu-latest' }}
      - name: 'Install xerces (macos)'
        run: |
          brew install xerces-c
        if: ${{ matrix.m.dds_security == 1 && matrix.m.os == 'macos-latest' }}
      - name: 'Configure & Build OpenDDS'
        run: |-
          if [ ${{ matrix.node_version }} == 16 ]; then
            CONFIG_OPTIONS+=" --std=c++14";
          else
            CONFIG_OPTIONS+=" --std=c++11";
          fi
          if [ ${{ matrix.m.dds_security }} == 1 ]; then
            CONFIG_OPTIONS+=" --security";
            BUILD_TARGETS+="OpenDDS_Security";
            if [ '${{ matrix.m.os }}' == 'macos-latest' ]; then
              CONFIG_OPTIONS+=" --xerces3=/usr/local/Cellar/xerces-c/3.2.3 --openssl=/usr/local/opt/openssl@1.1"
            fi
          fi
          echo "dds_security=${{ matrix.m.dds_security }}; CONFIG_OPTIONS=$CONFIG_OPTIONS; BUILD_TARGETS=$BUILD_TARGETS"
          cd OpenDDS
          ./configure --no-tests $CONFIG_OPTIONS
          cd ..
          make -C OpenDDS -sj6 DCPSInfoRepo_Main OpenDDS_Rtps_Udp $BUILD_TARGETS
      - name: 'Checkout nvm'
        uses: actions/checkout@v2
        with:
          repository: nvm-sh/nvm.git
          path: ${{ env.NVM_DIR }}
          ref: v0.39.0
          fetch-depth: 1
      - name: 'Install node, Build, Test'
        run: |-
          cd ${{ env.NVM_DIR }}
          [ -s "./nvm.sh" ] && \. "./nvm.sh"  # loads nvm
          cd $GITHUB_WORKSPACE
          nvm install ${{ matrix.node_version }}
          nvm use ${{ matrix.node_version }}
          echo "node:$(node -v) npm:$(npm -v)"
          export V8_ROOT=$NVM_INC/../..
          echo "Build ========== ========== =========="
          npm install
          ${{ env.ACE_ROOT }}/bin/mwc.pl -type gnuace -exclude ACE_TAO,OpenDDS
          make -j2 || make
          echo "Test ========== ========== =========="
          if [ ${{ matrix.m.dds_security }} == 1 ]; then TEST_OPTIONS+="--secure"; fi
          cd test;
          ./run_test.pl cpp2node $TEST_OPTIONS
          ./run_test.pl node2cpp $TEST_OPTIONS
          ./run_test.pl node2node $TEST_OPTIONS
          ./run_test.pl cpp2node --rtps
          ./run_test.pl node2cpp --rtps
          ./run_test.pl node2node --rtps
