---
name: "node-opendds Build & Test"
on:
  push:
    branches:
      - master
      - MigrateToGithubActions
  pull_request:
    branches:
      - master
jobs:
  Build:
    env:
      ACE_ROOT: $BUILD_DIR/ACE_TAO/ACE
      TAO_ROOT: $BUILD_DIR/ACE_TAO/TAO
      DDS_ROOT: $BUILD_DIR/OpenDDS
      MPC_ROOT: $BUILD_DIR/MPC
      LD_LIBRARY_PATH: $ACE_ROOT/lib:$DDS_ROOT/lib:$LD_LIBRARY_PATH
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 10
        include:
          - {os: osx, env: 'COMPILER=clang++ NO_INLINE=1 OPENDDS_BRANCH=master DDS_SECURITY=0'}
          - {os: osx, env: 'COMPILER=clang++ NO_INLINE=1 OPENDDS_BRANCH=latest-release DDS_SECURITY=0'}
          #- {os: linux, env: 'OPENDDS_BRANCH=master DDS_SECURITY=1'}
          #- {os: linux, env: 'OPENDDS_BRANCH=latest-release DDS_SECURITY=1'}
    runs-on: ${{ matrix.os }}
    steps:
      - if: runner.os == 'linux'
        name: Install dependencies (Ubuntu)
        run: |-
          sudo apt-get update
          sudo apt-get -y install libssl-dev libxerces-c-dev
      - name: 'Set up Node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v2
      - run: |-
          nvm install ${{ matrix.node-version }}
          nvm use ${{ matrix.node-version }}
          git clone --depth 1 git://github.com/DOCGroup/MPC.git
          git clone --depth 1 -b Latest_Micro git://github.com/DOCGroup/ACE_TAO.git
          git clone --depth 1 -b $OPENDDS_BRANCH git://github.com/objectcomputing/OpenDDS.git
          export
          cd OpenDDS
          if [ "$DDS_SECURITY" == 1 ]; then CONFIG_OPTIONS+="--security"; fi
          ./configure --no-tests --std=c++11 $CONFIG_OPTIONS
          cd ..
          export npm_config_devdir=$BUILD_DIR/opendds-node-gyp-devdir
          npm install -g node-gyp
          node-gyp install --ensure
          if [ "$DDS_SECURITY" == 1 ]; then BUILD_TARGETS+="OpenDDS_Security"; fi
          make -C OpenDDS -sj6 DCPSInfoRepo_Main OpenDDS_Rtps_Udp $BUILD_TARGETS
          npm install
          export V8_ROOT=$npm_config_devdir/$(node -v | cut -c 2-)
          export NAN_ROOT=$BUILD_DIR/node_modules/nan
          $ACE_ROOT/bin/mwc.pl -type gnuace -exclude ACE_TAO,OpenDDS
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$BUILD_DIR/tools/v8stubs
          make
          if [ "$DDS_SECURITY" == 1 ]; then TEST_OPTIONS+="--secure"; fi
          cd test;
          ./run_test.pl cpp2node $TEST_OPTIONS
          ./run_test.pl node2cpp $TEST_OPTIONS
          ./run_test.pl node2node $TEST_OPTIONS
